# Generated by Django 3.2.6 on 2021-10-29 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_taskreport_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='fahrtkosten',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Fahrtkosten'),
        ),
        migrations.AlterField(
            model_name='task',
            name='ub',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Üb'),
        ),
    ]
